packages:
  - '.'
  - 'server'
onlyBuiltDependencies:
  - ' '
  - '-'
  - /
  - '@'
  - '@swc/core'
  - b
  - better-sqlite3
  - c
  - core-js-bundle
  - d
  - e
  - esbuild
  - i
  - j
  - l
  - m
  - n
  - o
  - r
  - rs-module-lexer
  - s
  - u
  - unrs-resolver
  - v
  - w
  - x
